### ISSUE TITLE
make it clear how to go back to main menu

### ISSUE THREAD

**Issue by szamanr** [metalfoxdev/Raindrop#12]
## problem

when you open a view, e.g. hourly view, you're stuck - there's no way to go back to the main menu and e.g. see the daily view.

## solution

either:
after printing the view, show the main menu again so the user can make a choice

or:
in every view have some "back" command that will return to the main menu. e.g. by writing "main" in the prompt

**Comment by szamanr** [comment]
PS. ok i discovered that you can type "back" to go back. but i found that out randomly - it would be great to display this info to the user.

**Comment by metalfoxdev** [comment]
This feature will be present in the v2 update. The v2 update will be released when all the github issues are resolved and fixed.
