### ISSUE TITLE
create a CLI executable during installation

### ISSUE THREAD

**Issue by szamanr** [metalfoxdev/Raindrop#9]
this is a CLI app so i was expecting that after installation all i need to do is run `raindrop` from my terminal. instead, this didn't work, so i had to inspect the installation source code to find out that it only sets up a desktop entry which i need to click to run the app. this doesn't seem so useful for a CLI app.

it should be as simple as making an executable binary that calls `python3 main.py` and putting it in some standard path directory.

**Comment by metalfoxdev** [comment]
Hi, I am deeply sorry for not replying for 4 months (I have been busy with work). Anyways, I have read the changes from your pull request. The code is excellent, thank you very much for contributing to this little project!
